stages:
    - build
    - deploy
    - update-dependencies

build:
    image: gradle:jdk17
    stage: build
    only:
        - main
    except:
        - schedules
    artifacts:
        paths:
            - ./build/dist
    variables:
        USERNAME: $NEXUS_USER
        PASSWORD: $NEXUS_PWD
    script:
        - ./gradlew build

deploy:
    image: justtreme/lftp:4.8.1
    stage: deploy
    only:
        - main
    except:
        - schedules
    dependencies:
        - build
    script:
        - lftp -e "set sftp:auto-confirm yes; mirror -X .* -X .*/ --reverse --verbose ./build/dist /home; bye" -u $SFTP_USER,$SFTP_PWD sftp://89.163.129.221

renovate:
    image: renovate/renovate
    stage: update-dependencies
    only:
        - schedules
    script:
        - renovate --platform gitlab --token $RENOVATE_TOKEN $CI_PROJECT_PATH
