name: Challenges
version: '${version}'
main: com.laudynetwork.challenges.Challenges
api-version: 1.19

commands:
  timer:
    description: Function 'Timer'
  gamemode:
    description: GameMode recoded command
    aliases: [ gm ]
  location:
    description: command
  test:
    description: command
  gui:
    description: command